export const categoryTechnicalSkillSeed = [
  {
    name: 'Frontend',
  },
  {
    name: 'Backend',
  },
  {
    name: 'Database',
  },
  {
    name: 'DevOps',
  },
  {
    name: 'Mobile',
  },
  {
    name: 'Testing',
  },
  {
    name: 'Design',
  },
  {
    name: 'Other',
  },
];

export const technicalSkillSeed = [
  //fronetend
  { name: 'HTML', category: 'Frontend' },
  { name: 'CSS', category: 'Frontend' },
  { name: 'JavaScript', category: 'Frontend' },
  { name: 'React', category: 'Frontend' },
  { name: 'Vue.js', category: 'Frontend' },
  { name: 'Angular', category: 'Frontend' },
  { name: 'Svelte', category: 'Frontend' },
  { name: 'Bootstrap', category: 'Frontend' },
  { name: 'Tailwind CSS', category: 'Frontend' },
  { name: 'Sass', category: 'Frontend' },
  { name: 'Less', category: 'Frontend' },
  { name: 'Webpack', category: 'Frontend' },
  { name: 'Babel', category: 'Frontend' },
  { name: 'ESLint', category: 'Frontend' },
  { name: 'Prettier', category: 'Frontend' },
  { name: 'JQuery', category: 'Frontend' },
  { name: 'TypeScript', category: 'Frontend' },
  { name: 'Consumo API GraphQL', category: 'Frontend' },
  { name: 'Apollo Client', category: 'Frontend' },
  { name: 'Next.js', category: 'Frontend' },
  //Backend
  { name: 'Node.js', category: 'Backend' },
  { name: 'Python', category: 'Backend' },
  { name: 'Java', category: 'Backend' },
  { name: 'C#', category: 'Backend' },
  { name: 'Ruby', category: 'Backend' },
  { name: 'PHP', category: 'Backend' },
  { name: 'Go', category: 'Backend' },
  { name: 'Rust', category: 'Backend' },
  { name: 'Kotlin', category: 'Backend' },
  { name: 'Swift', category: 'Backend' },
  { name: 'TypeScript', category: 'Backend' },
  { name: 'Django', category: 'Backend' },
  { name: 'Flask', category: 'Backend' },
  { name: 'Spring Boot', category: 'Backend' },
  { name: 'ASP.NET', category: 'Backend' },
  { name: 'Ruby on Rails', category: 'Backend' },
  { name: 'Laravel', category: 'Backend' },
  { name: 'Express.js', category: 'Backend' },
  { name: 'GraphQL', category: 'Backend' },
  { name: 'Socket.IO', category: 'Backend' },
  // Database skills
  { name: 'SQL', category: 'Database' },
  { name: 'MySQL', category: 'Database' },
  { name: 'PostgreSQL', category: 'Database' },
  { name: 'MongoDB', category: 'Database' },
  { name: 'Oracle', category: 'Database' },
  { name: 'SQLite', category: 'Database' },
  { name: 'MariaDB', category: 'Database' },
  { name: 'Firebase', category: 'Database' },
  { name: 'Cassandra', category: 'Database' },
  { name: 'Redis', category: 'Database' },
  { name: 'Elasticsearch', category: 'Database' },
  { name: 'Neo4j', category: 'Database' },
  { name: 'InfluxDB', category: 'Database' },
  { name: 'CouchDB', category: 'Database' },
  { name: 'DynamoDB', category: 'Database' },
  { name: 'HBase', category: 'Database' },
  { name: 'Cosmos DB', category: 'Database' },
  { name: 'RethinkDB', category: 'Database' },
  { name: 'Couchbase', category: 'Database' },
  { name: 'Riak', category: 'Database' },

  // DevOps skills
  { name: 'Docker', category: 'DevOps' },
  { name: 'Kubernetes', category: 'DevOps' },
  { name: 'Jenkins', category: 'DevOps' },
  { name: 'Ansible', category: 'DevOps' },
  { name: 'Terraform', category: 'DevOps' },
  { name: 'AWS', category: 'DevOps' },
  { name: 'Azure', category: 'DevOps' },
  { name: 'Google Cloud', category: 'DevOps' },
  { name: 'Nginx', category: 'DevOps' },
  { name: 'Apache', category: 'DevOps' },
  { name: 'Shell Scripting', category: 'DevOps' },
  { name: 'Puppet', category: 'DevOps' },
  { name: 'Chef', category: 'DevOps' },
  { name: 'Vagrant', category: 'DevOps' },
  { name: 'VirtualBox', category: 'DevOps' },
  { name: 'VMware', category: 'DevOps' },
  { name: 'OpenStack', category: 'DevOps' },
  { name: 'Rancher', category: 'DevOps' },

  // Mobile skills
  { name: 'Swift', category: 'Mobile' },
  { name: 'Objective-C', category: 'Mobile' },
  { name: 'Java', category: 'Mobile' },
  { name: 'Kotlin', category: 'Mobile' },
  { name: 'React Native', category: 'Mobile' },
  { name: 'Flutter', category: 'Mobile' },
  { name: 'Ionic', category: 'Mobile' },
  { name: 'Xamarin', category: 'Mobile' },
  { name: 'Cordova', category: 'Mobile' },
  { name: 'Unity', category: 'Mobile' },
  { name: 'Unreal Engine', category: 'Mobile' },
  { name: 'Cocos2d', category: 'Mobile' },
  { name: 'PhoneGap', category: 'Mobile' },
  { name: 'Appcelerator Titanium', category: 'Mobile' },
  { name: 'Sencha Touch', category: 'Mobile' },
  { name: 'Corona SDK', category: 'Mobile' },
  { name: 'Qt', category: 'Mobile' },
  { name: 'RubyMotion', category: 'Mobile' },
  { name: 'J2ME', category: 'Mobile' },
  { name: 'Firebase', category: 'Mobile' },

  // Testing skills
  { name: 'JUnit', category: 'Testing' },
  { name: 'TestNG', category: 'Testing' },
  { name: 'Selenium', category: 'Testing' },
  { name: 'Cucumber', category: 'Testing' },
  { name: 'Mocha', category: 'Testing' },
  { name: 'Jest', category: 'Testing' },
  { name: 'Enzyme', category: 'Testing' },
  { name: 'Chai', category: 'Testing' },
  { name: 'Postman', category: 'Testing' },
  { name: 'JMeter', category: 'Testing' },
  { name: 'LoadRunner', category: 'Testing' },
  { name: 'QTP', category: 'Testing' },
  { name: 'SoapUI', category: 'Testing' },
  { name: 'Appium', category: 'Testing' },
  { name: 'Protractor', category: 'Testing' },
  { name: 'Sinon.js', category: 'Testing' },
  { name: 'Karma', category: 'Testing' },
  { name: 'Cypress', category: 'Testing' },
  { name: 'Puppeteer', category: 'Testing' },
  { name: 'AVA', category: 'Testing' },

  // Design skills
  { name: 'Photoshop', category: 'Design' },
  { name: 'Illustrator', category: 'Design' },
  { name: 'InDesign', category: 'Design' },
  { name: 'Sketch', category: 'Design' },
  { name: 'Figma', category: 'Design' },
  { name: 'Adobe XD', category: 'Design' },
  { name: 'CorelDRAW', category: 'Design' },
  { name: 'GIMP', category: 'Design' },
  { name: 'InVision', category: 'Design' },
  { name: 'Zeplin', category: 'Design' },
  { name: 'Balsamiq', category: 'Design' },
  { name: 'Affinity Designer', category: 'Design' },
  { name: 'UXPin', category: 'Design' },
  { name: 'Marvel', category: 'Design' },
  { name: 'Proto.io', category: 'Design' },
  { name: 'Axure RP', category: 'Design' },
  { name: 'QuarkXPress', category: 'Design' },
  { name: 'Gravit Designer', category: 'Design' },
  { name: 'Canva', category: 'Design' },
  { name: 'Blender', category: 'Design' },

  // Other skills
  { name: 'Git', category: 'Other' },
  { name: 'GitHub', category: 'Other' },
  { name: 'Bitbucket', category: 'Other' },
  { name: 'GitLab', category: 'Other' },
  { name: 'SVN', category: 'Other' },
  { name: 'Mercurial', category: 'Other' },
  { name: 'Agile', category: 'Other' },
  { name: 'Scrum', category: 'Other' },
  { name: 'Kanban', category: 'Other' },
  { name: 'Waterfall', category: 'Other' },
  { name: 'TDD', category: 'Other' },
  { name: 'BDD', category: 'Other' },
  { name: 'DDD', category: 'Other' },
];
