export enum ContractTypeEnum {
  INTERNSHIP = 'INTERNSHIP',
  TEMPORARY = 'TEMPORARY',
  CONTRACTOR = 'CONTRACTOR',
  PERMANENT = 'PERMANENT',
  VOLUNTEER = 'VOLUNTEER',
  BY_PROJECT = 'BY_PROJECT',
}

export enum StatusEnum {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum WorkdayEnum {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  INTERMITTENT = 'INTERMITTENT',
}

export enum ExperienceLevelEnum {
  LESS_ONE_YEAR = 'LESS_ONE_YEAR',
  ONE_OR_TWO_YEARS = 'ONE_TO_THREE_YEARS',
  THREE_TO_FIVE_YEARS = 'THREE_TO_FIVE_YEARS',
  MORE_FIVE_YEARS = 'MORE_FIVE_YEARS',
}

export enum ModalityEnum {
  ON_SITE = 'ON_SITE',
  REMOTE = 'REMOTE',
  HYBRID = 'HYBRID',
}
